# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goctx < Formula
  desc "Command-line Go utility that automatically adds missing 'plumbing' for `context.Context` parameters along the call-graph leading to a given function."
  homepage "https://github.com/preminger/goctx"
  version "0.17.21"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/preminger/goctx/releases/download/v0.17.21/goctx_0.17.21_darwin_amd64.tar.gz"
      sha256 "9b118be8613316f6b8315d7d596dd62fd25b2fc6f2048793b190dd40403c15f7"

      define_method(:install) do
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/preminger/goctx/releases/download/v0.17.21/goctx_0.17.21_darwin_arm64.tar.gz"
      sha256 "29c1bfd462a18b880afec83b32137fdd980d2accfd932492b41d6350a425fbd4"

      define_method(:install) do
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/preminger/goctx/releases/download/v0.17.21/goctx_0.17.21_linux_amd64.tar.gz"
      sha256 "c20f48378d646492c7799a6f5359728f50e93d84f1ab81947950e8a0c4a9dbd9"
      define_method(:install) do
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/preminger/goctx/releases/download/v0.17.21/goctx_0.17.21_linux_arm.tar.gz"
      sha256 "f4c9cea6da1ea818e7a07646712104aeb6a34d68d9a5e8659fc3a11adffe1d82"
      define_method(:install) do
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/preminger/goctx/releases/download/v0.17.21/goctx_0.17.21_linux_arm64.tar.gz"
      sha256 "7e0298502453118a8f4d535b6f46298980085311ca952a2addc0e26bbf9ef2b8"
      define_method(:install) do
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions, you may need to add the following to your shell profile, and then open a new shell:
        zsh:
          autoload -U compinit && compinit
        bash:
          [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/goctx --version"
  end
end
