# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goctx < Formula
  desc "Command-line Go utility that automatically adds missing 'plumbing' for `context.Context` parameters along the call-graph leading to a given function."
  homepage "https://github.com/preminger/goctx"
  version "0.17.11"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/preminger/goctx/releases/download/v0.17.11/goctx_0.17.11_darwin_amd64.tar.gz"
      sha256 "460e98ed68e17bcfbf1598e068695aab24e162fcce38900020d0c936238e0ffd"

      def install
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/preminger/goctx/releases/download/v0.17.11/goctx_0.17.11_darwin_arm64.tar.gz"
      sha256 "7a1c23de30ab6bbbdd457d5b42dc3389bc247610261d510e5af1d86dd83d7ea4"

      def install
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/preminger/goctx/releases/download/v0.17.11/goctx_0.17.11_linux_amd64.tar.gz"
      sha256 "c14de4ad9f8e318df4b6ee9e3b28365b184251b03049182116af5511b4ade40a"
      def install
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/preminger/goctx/releases/download/v0.17.11/goctx_0.17.11_linux_arm.tar.gz"
      sha256 "e26cbec7815c875a90539cd3332394d909ce278e7cdc246b7676b935c8027f81"
      def install
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/preminger/goctx/releases/download/v0.17.11/goctx_0.17.11_linux_arm64.tar.gz"
      sha256 "0858dabe60b808f029e938dd439d2d0f276f611c8a7b35fb1bb3397999c8aaae"
      def install
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions, you may need to add the following to your shell profile, and then open a new shell:
        zsh:
          autoload -U compinit && compinit
        bash:
          [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/goctx --version"
  end
end
