# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goctx < Formula
  desc "Command-line Go utility that automatically adds missing 'plumbing' for `context.Context` parameters along the call-graph leading to a given function."
  homepage "https://github.com/preminger/goctx"
  version "0.17.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/preminger/goctx/releases/download/v0.17.9/goctx_0.17.9_darwin_amd64.tar.gz"
      sha256 "e3932116975e42296576f6b43c1aadeb8c6910fa47966ae38fb7de0bf2506747"

      def install
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/preminger/goctx/releases/download/v0.17.9/goctx_0.17.9_darwin_arm64.tar.gz"
      sha256 "329b4c58ff6525ecea31b1f89ba8d10d4eea19973be46074f1839de9c3b3ae16"

      def install
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/preminger/goctx/releases/download/v0.17.9/goctx_0.17.9_linux_amd64.tar.gz"
      sha256 "f990a096565ba97d6d85b8b9a08f2d09722cdfabc25dbe3ad557d7fa9aab7364"
      def install
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/preminger/goctx/releases/download/v0.17.9/goctx_0.17.9_linux_arm.tar.gz"
      sha256 "ef2e470ab97db70375f6dc95274734cd4f5641b8fc548f9308ee2844bf4cbeee"
      def install
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/preminger/goctx/releases/download/v0.17.9/goctx_0.17.9_linux_arm64.tar.gz"
      sha256 "5f41a17ac746c2ebe879187b376380886787b87c06cd17eb3a1b8ef6a4126d10"
      def install
        bin.install "goctx"
        bash_completion.install "completions/goctx.bash" => "goctx"
        zsh_completion.install "completions/goctx.zsh" => "_goctx"
        fish_completion.install "completions/goctx.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions, you may need to add the following to your shell profile, and then open a new shell:
        zsh:
          autoload -U compinit && compinit
        bash:
          [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/goctx --version"
  end
end
