# This file was generated by GoReleaser. DO NOT EDIT.
cask "goctx" do
  name "goctx"
  desc "Propagate context.Context through Go call graphs automatically."
  homepage "https://github.com/preminger/goctx"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goctx"

  on_macos do
    on_intel do
      url "https://github.com/preminger/goctx/releases/download/v#{version}/goctx_#{version}_darwin_amd64.tar.gz"
      sha256 "2b41d7a9a9eac8f8ba79f1f8f7e2c366985818b115260e78fd7f75831d72b18a"
    end
    on_arm do
      url "https://github.com/preminger/goctx/releases/download/v#{version}/goctx_#{version}_darwin_arm64.tar.gz"
      sha256 "04addc65af21c0c2596ff15e1cdc406d9d72d0f7133c87516188536aa2c28ba2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/preminger/goctx/releases/download/v#{version}/goctx_#{version}_linux_amd64.tar.gz"
      sha256 "c56e64948a87f6f1ef0fa706b0a7309e31f0e17b3499902e069f78b5c8738918"
    end
    on_arm do
      url "https://github.com/preminger/goctx/releases/download/v#{version}/goctx_#{version}_linux_arm64.tar.gz"
      sha256 "b766450d0fc99cf72ce39b1e82dbb59213045dee99f1d31093e29fd866f92483"
    end
  end

  # No zap stanza required
end
